Updating Covid Forecast Hub website - no longer accepting submissions
reichlab/covid19-forecast-hub-web pull request #115
Opened 2024-04-30 19:22 UTC by micokoch

2024-05-01 00:26 UTC, nickreich commented on doc/ensemble/index.md
> +The forecast hub currently collaborated with CDC on the production of four ensemble forecasts each week:
remove "currently"

2024-05-01 00:31 UTC, nickreich commented on index.md
How about changing the text on line 9 that appears in the center of the page rather than adding the new grid item?   

Maybe
"As of Wednesday, May 1, 2024, the US COVID-19 Forecast Hub stopped accepting forecast submissions. From 2020 to 2024, this site collected real-time forecasts of COVID-19 hospitalizations, cases and deaths for the US, created by dozens of leading infectious disease modeling teams from around the globe, in coordination with the US CDC."

2024-05-01 00:32 UTC, nickreich requested changes
Thanks for catching the publications and the needed tense changes. I have a few suggested revisions as comments.

2024-05-01 09:31 UTC, micokoch commented on index.md
Hi Nick, I made the edit that you suggested and also fixed some of the text in the grid items.

2024-05-01 09:34 UTC, micokoch commented
Thanks for the review, Nick. I made the changes you suggested and a couple of more fixes on the landing page. I hope that works.

2024-05-06 16:25 UTC, micokoch commented
Hi @nickreich - I deleted all sentences about restarting in the fall of 2024 and this should be ready to merge.

2024-05-06 16:40 UTC, nickreich approved these changes

2024-05-06 16:40 UTC, merged